package ui;

public class PageHREmployeeRecords extends javax.swing.JFrame {

    public PageHREmployeeRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeRecordsTable = new javax.swing.JTable();
        ownRecordButton = new util.LightButton();
        newEmployeeButton = new util.LightButton();
        backButton = new util.LightButton();
        statusFilter = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 51, 51));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("Filter by Status:");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 110, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        employeeRecordsTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        employeeRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Account Status", "Employment Status", "Last Name", "First Name", "Birthdate", "Contact Number", "Address", "Position", "Department", "SSS No.", "Philhealth No.", "TIN No.", "Pag-Ibig No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeRecordsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        employeeRecordsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeRecordsTable.setMaximumSize(new java.awt.Dimension(3000, 80));
        employeeRecordsTable.setMinimumSize(new java.awt.Dimension(3000, 80));
        employeeRecordsTable.setPreferredSize(new java.awt.Dimension(3000, 80));
        employeeRecordsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(employeeRecordsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 940, 400));

        ownRecordButton.setForeground(new java.awt.Color(0, 102, 102));
        ownRecordButton.setText("View Own Record");
        ownRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownRecordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ownRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 210, -1));

        newEmployeeButton.setForeground(new java.awt.Color(0, 102, 102));
        newEmployeeButton.setText("New Employee");
        getContentPane().add(newEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 150, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        statusFilter.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        statusFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Active", "Pending", "Deactivated" }));
        getContentPane().add(statusFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 84, 140, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/HREmployeeRecords.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ownRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownRecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownRecordButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Back to Employee Home
        new PageHRHome().setVisible(true);
        this.dispose(); // Close current page
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageHREmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageHREmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageHREmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageHREmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageHREmployeeRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JTable employeeRecordsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label9;
    private util.LightButton newEmployeeButton;
    private util.LightButton ownRecordButton;
    private javax.swing.JComboBox<String> statusFilter;
    // End of variables declaration//GEN-END:variables
}
