/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author STUDY MODE
 */
public class PageManagerHome extends javax.swing.JFrame {

    /**
     * Creates new form PageManagerHome
     */
    public PageManagerHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateTimeText = new javax.swing.JLabel();
        leavesAvailableText = new javax.swing.JLabel();
        totalWorkedHoursText = new javax.swing.JLabel();
        clockInButton = new util.BlueButton();
        clockOutButton = new util.BlueButton();
        fullNameText = new javax.swing.JLabel();
        positionText = new javax.swing.JLabel();
        employeeDataButton = new util.BlueButton();
        attendanceButton = new util.BlueButton();
        payslipButton = new util.BlueButton();
        leaveButton = new util.BlueButton();
        overtimeButton = new util.BlueButton();
        logoutButton = new util.LightButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateTimeText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dateTimeText.setForeground(new java.awt.Color(0, 102, 102));
        dateTimeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTimeText.setText("Date & Time Here");
        getContentPane().add(dateTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 400, 110));

        leavesAvailableText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        leavesAvailableText.setForeground(new java.awt.Color(0, 153, 153));
        leavesAvailableText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesAvailableText.setText("0");
        getContentPane().add(leavesAvailableText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 80, -1));

        totalWorkedHoursText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalWorkedHoursText.setForeground(new java.awt.Color(0, 153, 153));
        totalWorkedHoursText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalWorkedHoursText.setText("0");
        getContentPane().add(totalWorkedHoursText, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 80, -1));

        clockInButton.setForeground(new java.awt.Color(0, 102, 102));
        clockInButton.setText("Clock-In");
        getContentPane().add(clockInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 180, -1));

        clockOutButton.setForeground(new java.awt.Color(0, 102, 102));
        clockOutButton.setText("Clock-Out");
        getContentPane().add(clockOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 180, -1));

        fullNameText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullNameText.setForeground(new java.awt.Color(0, 102, 102));
        fullNameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullNameText.setText("Manager");
        getContentPane().add(fullNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 190, -1));

        positionText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        positionText.setForeground(new java.awt.Color(0, 102, 102));
        positionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionText.setText("Position");
        getContentPane().add(positionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, -1));

        employeeDataButton.setForeground(new java.awt.Color(0, 102, 102));
        employeeDataButton.setText("Employee Data");
        getContentPane().add(employeeDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 180, -1));

        attendanceButton.setForeground(new java.awt.Color(0, 102, 102));
        attendanceButton.setText("Attendance");
        getContentPane().add(attendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 180, -1));

        payslipButton.setForeground(new java.awt.Color(0, 102, 102));
        payslipButton.setText("Payslip");
        getContentPane().add(payslipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 180, -1));

        leaveButton.setForeground(new java.awt.Color(0, 102, 102));
        leaveButton.setText("Leave");
        getContentPane().add(leaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 180, -1));

        overtimeButton.setForeground(new java.awt.Color(0, 102, 102));
        overtimeButton.setText("Overtime");
        getContentPane().add(overtimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 180, -1));

        logoutButton.setForeground(new java.awt.Color(0, 102, 102));
        logoutButton.setText("Logout");
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Home.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageManagerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private util.BlueButton attendanceButton;
    private util.BlueButton clockInButton;
    private util.BlueButton clockOutButton;
    private javax.swing.JLabel dateTimeText;
    private util.BlueButton employeeDataButton;
    private javax.swing.JLabel fullNameText;
    private util.BlueButton leaveButton;
    private javax.swing.JLabel leavesAvailableText;
    private util.LightButton logoutButton;
    private util.BlueButton overtimeButton;
    private util.BlueButton payslipButton;
    private javax.swing.JLabel positionText;
    private javax.swing.JLabel totalWorkedHoursText;
    // End of variables declaration//GEN-END:variables
}
